[tool.ruff]

line-length = 100
target-version = "py310"

[tool.ruff.lint]

select = ["A", "B", "C", "D", "E", "F", "I", "N", "PL", "R", "UP", "W"]
ignore = ["D100", "D101", "D102", "D103", "D105", "D107", "D203", "D213", "PLR2004"]
